spring:
  cloud:
    gateway:
      routes:
      - id: CRYPTOSERVICE
        uri: http://localhost:8082
        predicates:
        - Path=/cryptousers/**, /cryptouser/**, /watchlists/**, /watchlist/**, /login
        
        
      - id: ENQUIRYSERVICE
        uri: http://localhost:8081
        predicates:
        - Path=/enquiry/**, /enquiries